### ISSUE TITLE
Unable To Scroll

### ISSUE THREAD

**Issue by SenatorSteven** [racketlogger/ModernKiosk#10]
I cannot scroll down or up for **sh*t** using the mouse wheel. Clicking the wheel and then moving the mouse pointer, on the other hand, works *mighty fine*.

Tested on YouTube and random Google Searches on Ubuntu 17.10. (Aye, you never know)

**Comment by cpg** [comment]
Working on this, however, there is some difficulty in finding out the reason scrolling is not working any more and how to fix it.

**Comment by cpg** [comment]
Can't reproduce. Please do re-open it if you can upgrade to the latest release of the plugin and it still happens.
