### ISSUE TITLE
Enable Kiosk without having a specific URL attached to the request

### ISSUE THREAD

**Issue by Christinahoff** [racketlogger/ModernKiosk#11]
I need to use Kiosk mode only when delivering a test to a candidate and the URL for each candidate is always different, so I'd like to be able to browse to the URL then turn on Kiosk mode.

**Comment by cpg** [comment]
You can do this today in two ways. Browse to the url, then either right click on the extension icon or on the screen and access the MK right-click menu. Select `Set current URL as kiosk URL` then start the kiosk.

I think that's what you want.
