### ISSUE TITLE
Fullscreen not working on Firefox ESR 60

### ISSUE THREAD

**Issue by malthuis** [racketlogger/ModernKiosk#12]
With firefox version 65 on ubuntu everything works as expected. Keep up the good work :)

With firefox 60 esr however the page is not displayed in fullscreen mode. Could you dig into that?

Thank you in advance :)

Kind regards,
Marin

**Comment by malthuis** [comment]
PS: using the snap package in ubuntu 18.10. Will test on other environments as well.

**Comment by cpg** [comment]
Should be working now in the latest release. If not, reopen.
