### ISSUE TITLE
ModernKiosk can not be added to Firefox on Linux

### ISSUE THREAD

**Issue by hecaxmmx** [racketlogger/ModernKiosk#14]
ModernKiosk fail since bug [https://github.com/mozilla/addons/issues/851](https://github.com/mozilla/addons/issues/851).
This issue has been fixed but you need to re-build the extension (package) and send again to [addons.mozilla.org](https://addons.mozilla.org)

![image](https://user-images.githubusercontent.com/9746174/59539366-37a2fb00-8eba-11e9-9b0f-47c67b76c900.png)

Extensions packaged recently do not present such a problem, e.g. [https://addons.mozilla.org/en-US/firefox/addon/fx-osk/?src=search](https://addons.mozilla.org/en-US/firefox/addon/fx-osk/?src=search)

**Comment by cpg** [comment]
Thanks for pointing this out.

I cannot seem to submit [a new version to the add-ons site](https://www.dropbox.com/s/z9mq5ko01ozusix/Screen%20Shot%202019-06-16%20at%201.34.56%20AM.png?dl=0)

**Comment by cpg** [comment]
Released [version 10](https://addons.mozilla.org/en-US/firefox/addon/modern-kiosk/)

Please check see if it works well and close this issue if it does.

**Comment by hecaxmmx** [comment]
Hi Carlos
I will test this tomorrow, I don't have Linux installed in my PC at home.

**Comment by hecaxmmx** [comment]
Tested in Linux Debian and works Ok.
