### ISSUE TITLE
Problems viewing PDFs

### ISSUE THREAD

**Issue by chillje** [racketlogger/ModernKiosk#9]
All PDFs viewing with function "serve local content" opens in browser "full outzoomed". I have to manually zoom in to see the pages in a "normal way".
Working on newest Chrome (65.0.3325.181) on newest Windows 10 (16299.309).

**Comment by cpg** [comment]
I'm not sure how you reached here, but this seems like some local configuration and entirely unrelated to ModernKiosk.
